# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: 
  vmImage: windows-latest

steps:
- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestPreRelease'

- task: Maven@3
  inputs:
    mavenPomFile: 'CrunchifyJunitTest/pom.xml'
    publishJUnitResults: true
    testResultsFiles: 'CrunchifyJunitTest/target/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'CrunchifyJunitTest/target/surefire-reports/TEST-*.xml'

- task: JavaTestBridgeForTestPlan@1
  inputs:
    testResultPath: 'CrunchifyJunitTest/target/surefire-reports'
    outputFolder: 'CrunchifyJunitTest/target'
    inputType: 'string'
    jsonMapping: '[{''workItemID'':26,''methodName'':''testingHelloWorld'',''className'':''com.crunchify.junit.CrunchifyJunitTest''}]'
    username: 'VSTToken'
    password: 's4x5oobh2lr374zghav7n2pequfvrtpkbtrkjxkr425tf3eekzuq'

- task: VSTest@3
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    vsTestVersion: 'toolsInstaller'